"$schema" = 'https://starship.rs/config-schema.json'
add_newline = true
command_timeout = 1000

[character]
success_symbol = '[â†’](green)'
error_symbol = '[â†’](red)'
vimcmd_symbol = '[â†](green)'
vimcmd_replace_one_symbol = '[â†](purple)'
vimcmd_replace_symbol = '[â†](purple)'
vimcmd_visual_symbol = '[â†](yellow)'

[git_branch]
symbol = 'ğŸŒµ'

[aws]
disabled = true

[gcloud]
disabled = true

[openstack]
disabled = true
