"$schema" = 'https://starship.rs/config-schema.json'
add_newline = false
command_timeout = 3000
format = """
$username\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$nodejs\
$sudo\
$line_break\
$jobs\
$battery\
$container\
$character
"""

[directory]
fish_style_pwd_dir_length = 1
home_symbol = 'ğŸ°'

[character]
success_symbol = '[â†’](green)'
error_symbol = '[â†’](red)'
vimcmd_symbol = '[â†](green)'
vimcmd_replace_one_symbol = '[â†](purple)'
vimcmd_replace_symbol = '[â†](purple)'
vimcmd_visual_symbol = '[â†](yellow)'

[git_branch]
symbol = 'ğŸŒµ'

[git_status]
ahead = 'â†‘'
behind = 'â†“'

[sudo]
disabled = false

[time]
disabled = false
