[[mgr.prepend_keymap]]
on = "q"
run = "quit --no-cwd-file"
desc = "Exit without changing the current directory"

[[mgr.prepend_keymap]]
on = "Q"
run = "quit"
desc = "Exit and change the current directory"
